port: 4444
# Site
repository: https://github.com/tristanberezowski/tristanberezowski.github.io
favicon: images/man.png

# Personal info
name: Tristan Berezowski
title: Full Stack Web Developer | Software Developer
email: tristanberezowski@gmail.com
phone: 604-219-9134
# website: bere.dev

# Social links
github_username:  tristanberezowski
linkedin_username: tristanberezowski

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I'm a full stack web developer who loves challenging logic puzzles and finding creative solutions to make a product stand out. My interest in coding began five years ago, however my experiences learning new techniques and problem solving daily have confirmed my passion for software development. I am eager to take on opportunities to work with positive people on projects which allow me to both display my  drive and continue my learning.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
skills_title: Skills #(Use this to override about more section title)
skills_content: | # this will include new lines to allow paragraphs
   I am very skilled

# Footer
#footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

slider:
  text_color: black
  shadow_color: black
  slides: 
    - image: "https://www.seoclerks.com/files/user/community/000/611/853/4c35d9cef7b143a4e17f4ce4e9a840a7--soccer-logo-logo-branding.1502284766.jpg"
      slide_html: "<p>JSX/React/HTML/SCSS/Node.js/WebSocket/Babel</p>"
    - image: "/images/profile.png"
      slide_html: "<p>Test</p>"
    - image: "/images/profile.png"
      slide_html: "<p>Test</p>"
